name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: ["3.10"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: bedtools
      run: |
        sudo apt-get install -y bedtools
    - name: Install the package itself
      run: |
          pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov-report term --cov=telofinder

    #- name: coveralls            
    #  run: |
    #    pip install coverage
    #    coveralls --service=github
    #  env:
    #      GITHUB_TOKEN: ${{ github.token }}
          
