name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: ["3.10", "3.11"]
      fail-fast: false

    steps:
    - uses: mamba-org/setup-micromamba@v1
      with:
          micromamba-version: '1.3.1-0'
          cache-environment: true
          environment-name: installation
          condarc: |
              channels:
                  - conda-forge
                  - bioconda
                  - defaults
          create-args: >-
            python=${{ matrix.python }}
            bedtools
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Install the package itself
      shell: bash -el {0}
      run: pip install .
      
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov-report term --cov=telofinder

    #- name: coveralls            
    #  run: |
    #    pip install coverage
    #    coveralls --service=github
    #  env:
    #      GITHUB_TOKEN: ${{ github.token }}
          
